{
 "title": "Default",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Statuses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "app_http_response_status" }
   ]
  },
  {
   "title": "request total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "app_http_requests_total" }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(app_http_requests_total[1m])"
    }
   ]
  },
  {
   "title": "Avg request dur",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "app_http_response_time_seconds_sum / app_http_response_time_seconds_count"
    }
   ]
  }
 ]
}