{
 "title": "Balancer",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Total request (last 2 hours)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(balancer_app_proxy_distribution[2h])))"
    }
   ]
  },
  {
   "title": "Total success request (last 2 hours) ",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(balancer_app_proxy_distribution{success='true'}[2h])))"
    }
   ]
  },
  {
   "title": "Average request evaluation duration (sec)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(balancer_app_response_time_seconds_sum[1h])) / sum(rate(balancer_app_response_time_seconds_count[1h]))"
    }
   ]
  },
  {
   "title": "Requests distribution (success)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "balancer_app_proxy_distribution{success='true'}"
    }
   ]
  },
  {
   "title": "Balancing distibution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum(balancer_app_proxy_distribution) by (server)"
    }
   ]
  },
  {
   "title": "Count of requests duration by method and server",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(rate(balancer_app_response_time_seconds_sum[5m])) by (method, server)"
    }
   ]
  }
 ]
}